module.exports = {
    ///////////////////////////////////////////////////////
    // TEXTUAL SUGGESTION
    ///////////////////////////////////////////////////////
	0 : { "fr" : "Suggérer plus d'expansion", "en" : ""},
	1 : { "fr" : "Vous restez trop dans une logique de dominante design", "en" : ""},
	2 : { "fr" : "Il y a un bon partage entre les concepts de rupture et incrémentale", "en" : ""},
	3 : { "fr" : "Ca va nous aider à structurer les roadMap court, moyen et long terme", "en" : ""},
	4 : { "fr" : "Il faut d'avantage travailler en K", "en" : ""},
	5 : { "fr" : "On est dans une volonté de rupture: il faut reprendre le travail en divergence et renforcer le travail en expansion", "en" : ""},
	6 : { "fr" : "Reprendre le travail d'expansion et de divergence", "en" : ""},
	7 : { "fr" : "Reprendre le travail d'expansion et de divergence", "en" : ""},
	8 : { "fr" : "reprendre le travail d’expansion et de divergence mais avec un travail sur les K encore plus fort notamment avec le lien sur les K indécidables", "en" : ""},
	9 : { "fr" : "on renforce l’originalité de manière forte", "en" : ""},
	10 : { "fr" : "on renforce l’originalité de manière très forte", "en" : ""},
	11 : { "fr" : "plus j’ai des partition expansive plus je vais vers de la rupture", "en" : ""},
	12 : { "fr" : "plus j’ai des partition restrictive plus je vais vers de l’incrémentale ", "en" : ""},
	13 : { "fr" : "toutes vos connaissances sont manquantes il faut aller les chercher à l’extérieur, avez vous la capacité à absorber de nouvelle connaissance?", "en" : ""},
	14 : { "fr" : "il faut qu’elle embauche", "en" : ""},
	15 : { "fr" : "qu’elle achète la connaissance en externe", "en" : ""},
	16 : { "fr" : "quelle fasse appel à un expert", "en" : ""},
	17 : { "fr" : "voir évaluation KSOR", "en" : ""},
	18 : { "fr" : "il n’y a pas de programme de recherche ou d’innovation en cour", "en" : ""},
	19 : { "fr" : "il faut lancer des programmes de recherche et d’innovation", "en" : ""},
	20 : { "fr" : "identifier les connaissances à acquérir et à valider en fonction des concepts (faire le lien avec le web)", "en" : ""},
	21 : { "fr" : "j’ai toute les K pour répondre à de nouveaux C", "en" : ""},
	22 : { "fr" : "vous aide dans une situation de moyen et grd delta C et de petit delta K", "en" : ""},
	23 : { "fr" : "vous pouvez aller assez vite pour mettre en place l’innovation", "en" : ""},
	24 : { "fr" : "(voir ex chaine de produit fluidisé ALCAN)", "en" : ""},
	25 : { "fr" : "diminue fortement le risque", "en" : ""},
	26 : { "fr" : "générer de nouveau concept pour produire du K", "en" : ""},
	27 : { "fr" : "il faut remonter sur les C hamecon developper des C hamecon", "en" : ""},
	28 : { "fr" : "proposer des crazy concepts", "en" : ""},
	29 : { "fr" : "augmente le niveau de risque ", "en" : ""},
	30 : { "fr" : "faire une cotation KSOR", "en" : ""},
	31 : { "fr" : "grd delta C petit delta K peu de risque", "en" : ""},
	32 : { "fr" : "roadmap cour et moyen terme", "en" : ""},
	33 : { "fr" : "voir les règles d’expansion en C", "en" : ""},
	34 : { "fr" : "reprendre le travail de divergence pour forcer l’expansion", "en" : ""},
	35 : { "fr" : "rechercher de nouvelles connaissances et travailler avec de nouveau expert ", "en" : ""},
	36 : { "fr" : "bonne indication sur les possibilités de structurer des road map pour l’exploration", "en" : ""},
	37 : { "fr" : "spécifier la suggestion en faisant le lien entre les delta C et delta K qui nous donnera le delta T", "en" : ""},
	38 : { "fr" : "Il faut aller chercher des compétences extérieurs (suggérer le type de profil qu’il manque)", "en" : ""},
	39 : { "fr" : "augmente l’interet du projet innovant", "en" : ""},
	40 : { "fr" : "ca va renvoyer vers une expansion de C et/ou une conjonction", "en" : ""},
	41 : { "fr" : "êtes vous en mesure de faire une conjonction? Une preuve de concept?", "en" : ""},
	42 : { "fr" : "Le risque est plus important", "en" : ""},
	43 : { "fr" : "Il faut monter des partenariats (suggérer des partenariats intéressant en fonction de la thématique voir si ya pas moyen de s’interfacer à l’api de linkedin ou https://www.jacoop.fr/ ou l’entreprise qui fait collaborer les grandes entreprise et les startups?)", "en" : ""},
	44 : { "fr" : "comment identifier des collaboration à partir des arbres CK (valeo et le modèle opéra)", "en" : ""},
	45 : { "fr" : "Votre base de connaissance est robuste", "en" : ""},
	46 : { "fr" : "Le risque est plus faible", "en" : ""},
	47 : { "fr" : "capacité d’absorption de nouveau K voir KSOR", "en" : ""},
	48 : { "fr" : "c hamecon + c indessidable = le plus en rupture scientifiquement ", "en" : ""},
	49 : { "fr" : "aller voir les bulles les première suggestion (avec ou sans description)", "en" : ""},
	50 : { "fr" : "j’ai un delta C plus fort et un delta K plus faible notamment pour des K existant > K nouvelle", "en" : ""},
	51 : { "fr" : "petit delta C avec des grd delta K", "en" : ""},
	52 : { "fr" : "choisir les k qui ne sont liées à aucun c et leur demander si elles peuvent engendrer des pistes de concepts?", "en" : ""},
	53 : { "fr" : "A chaque concept doit correspondre une connaissance", "en" : ""},
	54 : { "fr" : "Lister les C non liés", "en" : ""},
	55 : { "fr" : "A chaque connaissance doit correspondre un concept", "en" : ""},
	56 : { "fr" : "Lister les K non liées", "en" : ""},
	57 : { "fr" : "elle est critique pour des innovations", "en" : ""},
	58 : { "fr" : "elle est critique dans le renouvellement des K et des métiers", "en" : ""},
	59 : { "fr" : "si elle est manquante/indécidable  il faut mettre le paquet dessus pour l’acquérir car elle va avoir le plus de retombée", "en" : ""},
	60 : { "fr" : "K à réintégrer, qu’on aurait oublié qui peut nous débloquer en C", "en" : ""},
	61 : { "fr" : "ca peu servir pour une innovation conceptuelle rapide", "en" : ""},
	62 : { "fr" : "insuffisamment mobilisé (ya til une raison?)", "en" : ""},
	63 : { "fr" : "partition en rupture fortes", "en" : ""},
	64 : { "fr" : "régénération des connaissance et des métiers", "en" : ""},
	64 : { "fr" : "si la moyenne est base et qu’on a beaucoup de feuille:", "en" : ""},
	65 : { "fr" : "si j’ai beaucoup de branche mais pas trop profond = on va vers de la rupture", "en" : ""},
	66 : { "fr" : "si la moyenne est haute et qu’on a beaucoup de feuille: ", "en" : ""},
	67 : { "fr" : "on va vers de la rupture et de la conjonction", "en" : ""},
	68 : { "fr" : "détaillé plus forte dominante design (avez-vous une dimension écosystème, business eco, system, sous-system?)", "en" : ""},
	69 : { "fr" : "avez vous la profondeur qui vous permet de traiter la problématique de la façon la plus large et la plus ouverte possible.", "en" : ""},
	70 : { "fr" : "Leur suggérer une catégorie", "en" : ""},
	71 : { "fr" : "Pourquoi cette poche est vide? Voici ce que nous avons trouvé sur le web pour vous en rapport avec cette catégorie cela vous inspire t-il?", "en" : ""},
	72 : { "fr" : "il faut au moins 3 ou 4 feuilles pour avoir un bon travail en expansion", "en" : ""},
	73 : { "fr" : "= le degré d’ouverture vers de nouvelles connaissances lié à l’expansion CK", "en" : ""},
	74 : { "fr" : "= originalité et du degré d’ouverture (ou de rupture)", "en" : ""},
	75 : { "fr" : "= originalité (et est donc lié au degré d’ouverture)", "en" : ""},
	76 : { "fr" : " traduire un degré douverture.", "en" : ""},
}